apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-deployer
  namespace: kallepallirupesh-dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-deployer-role
  namespace: kallepallirupesh-dev
rules:

- apiGroups: [""]
  resources:
    - pods
    - services
    - configmaps
    - secrets
    - serviceaccounts
    - persistentvolumeclaims
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-deployer-binding
  namespace: kallepallirupesh-dev
subjects:
  - kind: ServiceAccount
    name: helm-deployer
    namespace: kallepallirupesh-dev
roleRef:
  kind: Role
  name: helm-deployer-role
  apiGroup: rbac.authorization.k8s.io