apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:

      # 🔥 NGINX
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: media-storage
            mountPath: /data

          # ✅ FIX: writable runtime dir
          - name: nginx-run
            mountPath: /run

          # ✅ OPTIONAL: cache dir (recommended)
          - name: nginx-cache
            mountPath: /var/cache/nginx

          - name: nginx-config
            mountPath: /etc/nginx/conf.d
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false

      # 🔥 FASTAPI
      - name: fastapi
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: BASE_URL
            value: {{ .Values.baseUrl }}
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: media-storage
            mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false

      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc

        - name: nginx-config
          configMap:
            name: nginx-config

        # ✅ FIX: runtime writable
        - name: nginx-run
          emptyDir: {}

        # ✅ OPTIONAL: cache
        - name: nginx-cache
          emptyDir: {}