apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: storage-service
spec:
  to:
    kind: Service
    name: storage-service
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None