apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: storage-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080