apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: image-gen-service
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/rupesh-kallepelli/instagram-automation.git"
      ref: "main"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: image-gen-service:latest
  triggers:
    - type: GitHub
    - type: ConfigChange
