on:
  workflow_dispatch:
  schedule:
    #Every day at 6 am IST
    - cron: '0 23 * * *'
    #Every day at 9:00 pm IST
    - cron: '05 15 * * *'
name: Wake Up n8n
jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} \
            --token=${{ secrets.OPENSHIFT_TOKEN }} \
            --insecure-skip-tls-verify

      - name: Select project
        run: |
          oc project ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Deployment rollout restart
        run: |
          oc scale deployment n8n --replicas=0
          sleep 10
          oc scale deployment n8n --replicas=1